pyverts/cats/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    #url(r'^(?P<gallery_id>\d+)/$', 'galleries.views.view', name='gallery'),
    #url(r'^(?P<gallery_id>\d+)/item/', include('galleries.items.urls')),
    url(r'^races/$', 'cats.views.json_races'),
    url(r'^create/$', 'cats.views.create', name='create_cat'),
    url(r'^delete/(?P<cat_id>\d+)/$', 'cats.views.delete', name='delete_cat'),
)

pyverts/pyverts/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'pyverts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^cats/', include('cats.urls')),
    url(r'^category/', include('products.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pyverts/cats/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField

from django.db.models.signals import post_save

class Basket(models.Model):
    owner = models.OneToOneField(User)

class Nature(models.Model):
    name = models.CharField(max_length=200, blank=False)
    calm = models.IntegerField(default=0)
    playful = models.IntegerField(default=0)
    cuddly = models.IntegerField(default=0)
    independent = models.IntegerField(default=0)
    noisy = models.IntegerField(default=0)
    kindness = models.IntegerField(default=0)
    socialness = models.IntegerField(default=0)
    scampish = models.IntegerField(default=0)
    robust = models.IntegerField(default=0)
    sexual_activity = models.IntegerField(default=0)
    tidyness = models.IntegerField(default=0)
    fluffyness = models.IntegerField(default=0)
    dirtyness = models.IntegerField(default=0)
    first_cat = models.IntegerField(default=0)
    originality = models.IntegerField(default=0)
    budget = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

class Race(models.Model):
    name = models.CharField(max_length=100, blank=False)
    nature = models.ForeignKey(Nature, null=True)
    adult_image = ImageField(upload_to='races', null=True, blank=True)
    young_image = ImageField(upload_to='races', null=True, blank=True)

    def __unicode__(self):
        return self.name

class Cat(models.Model):
    basket = models.ForeignKey(Basket)
    race = models.ForeignKey(Race)
    name = models.CharField(max_length=100, blank=False)

    def __unicode__(self):
        return self.name

def create_user_basket(sender, instance, created, **kwargs):
    if created:
        Basket.objects.create(owner=instance)

post_save.connect(create_user_basket, sender=User)

pyverts/cats/forms.py
from django.forms import ModelForm
from cats.models import Cat

class CatForm(ModelForm):
    class Meta:
        model = Cat
        fields = ('name','race')

pyverts/cats/views.py
# -*- coding: utf-8 -*- 
from django.contrib.auth.decorators import login_required

from django.shortcuts import render

from cats.models import Basket, Cat, Race, Nature
from cats.forms import CatForm

from django.shortcuts import redirect

from django.shortcuts import get_object_or_404

from django.core.exceptions import PermissionDenied

import json
from django.http import HttpResponse

from sorl.thumbnail import get_thumbnail

@login_required
def create (request):
    form = CatForm();
    basket = Basket.objects.get(owner=request.user)
    races = Race.objects.all()
    if request.method == "POST":
        form = CatForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=False)
            cat.basket = basket
            cat.save()
            return redirect('my_profile')
    return render(request, 'cats/create.html', {'form': form, 'races': races})

@login_required
def delete (request, cat_id):
    cat = get_object_or_404(Cat, id=cat_id)
    if cat.basket.owner != request.user:
        raise PermissionDenied
    cat.delete()
    return redirect('my_profile')

def json_races (request):
    races = Race.objects.all()
    obj = {'races': []}
    for race in races:
        race_obj = {}
        race_obj['name'] = race.name
        race_obj['img'] = get_thumbnail(race.young_image, '150x150', crop='center').url
        race_obj['calm'] = race.nature.calm
        race_obj['playful'] = race.nature.playful
        race_obj['cuddly'] = race.nature.cuddly
        race_obj['independent'] = race.nature.independent
        race_obj['noisy'] = race.nature.noisy
        race_obj['kindness'] = race.nature.kindness
        race_obj['socialness'] = race.nature.socialness
        race_obj['scampish'] = race.nature.scampish
        race_obj['robust'] = race.nature.robust
        race_obj['sexual_activity'] = race.nature.sexual_activity
        race_obj['tidyness'] = race.nature.tidyness
        race_obj['fluffyness'] = race.nature.fluffyness
        race_obj['dirtyness'] = race.nature.dirtyness
        race_obj['first_cat'] = race.nature.first_cat
        race_obj['originality'] = race.nature.originality
        race_obj['budget'] = race.nature.budget
        obj['races'].append(race_obj)
    return HttpResponse(json.dumps(obj, indent=4), content_type="application/json")

pyverts/templates/cats/create.html
{% extends "base.html" %}
{% load i18n %}
{% load account %}
{% load bootstrap3 %}

{% load thumbnail %}

{% block head_title %}{% trans "Ajout d'un nouveau chat" %}{% endblock %}

{% block body %}
<div class="row">
<div class="col-md-8">
<a class="btn btn-primary btn-sm" href="{% url 'my_profile' %}">« Retour aux chatons</a>
<h1>{% trans "Création d'un chaton" %}</h1>
<h2>{% trans "Nom du chaton" %}</h2>
<form action="{% url 'create_cat' %}" method="post">
    {% csrf_token %}
    <div class="form-group"><input type="text" title="" required="" placeholder="Entrez un nom super mignon !" name="name" maxlength="100" id="id_name" class="form-control input-lg"></div>
    
<h2>{% trans "Race du chaton" %}</h2>
<div class="row">
{% for race in races %}
<div class="col-md-3">
    <div class="thumbnail race">
    {% if race.adult_image %}
        {% thumbnail race.adult_image "150x150" crop="center" as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
    {% elif race.young_image %}
        {% thumbnail race.young_image "150x150" crop="center" as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
    {% else %}
        <img src="http://placekitten.com/150/150">
    {% endif %}
        <input type="radio" name="race" value="{{ race.id }}" style="display:none">
        <div class="caption">
            <h3 style="text-align: center">{{ race.name }}</h3>
        </div>
        <input type="hidden" class="calm" value="{{ race.nature.calm }}" />
        <input type="hidden" class="playful" value="{{ race.nature.playful }}" />
        <input type="hidden" class="cuddly" value="{{ race.nature.cuddly }}" />
        <input type="hidden" class="independent" value="{{ race.nature.independent }}" />
        <input type="hidden" class="noisy" value="{{ race.nature.noisy }}" />
        <input type="hidden" class="kindness" value="{{ race.nature.kindness }}" />
        <input type="hidden" class="socialness" value="{{ race.nature.socialness }}" />
        <input type="hidden" class="scampish" value="{{ race.nature.scampish }}" />
        <input type="hidden" class="robust" value="{{ race.nature.robust }}" />
        <input type="hidden" class="sexual_activity" value="{{ race.nature.sexual_activity }}" />
        <input type="hidden" class="tidyness" value="{{ race.nature.tidyness }}" />
        <input type="hidden" class="fluffyness" value="{{ race.nature.flufflyness }}" />
        <input type="hidden" class="dirtyness" value="{{ race.nature.dirtyness }}" />
        <input type="hidden" class="first_cat" value="{{ race.nature.first_cat }}" />
        <input type="hidden" class="originality" value="{{ race.nature.originality }}" />
        <input type="hidden" class="budget" value="{{ race.nature.budget }}" />
    </div>
</div>
{% endfor %}
</div>
{% buttons %}
    <button type="submit" class="btn btn-success btn-lg">
        {% trans "Créer" %}
    </button>
    {% endbuttons %}
</form>
</div>
<div class="col-md-4">
    <h3>Caractéristiques</h3>
    Calme
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="calm">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Joueur
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="playful">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Câlin
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="cuddly">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Indépendant
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="independent">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Miauleur
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="noisy">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Gentil
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="kindness">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Sociable
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="socialness">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Propreté
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="tidyness">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Originalité
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="originality">
            <span class="sr-only">0%</span>
          </div>
        </div>
        Luxe
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="budget">
            <span class="sr-only">0%</span>
          </div>
        </div>
</div>
</div>
{% endblock %}